exception_vadarneg_words:
  - Drunk
  - lack
  - puke
  - forget
  - weapons
  - emergency
  - lies
  - lag
  - ruining
  - stuck
  - blocked
  - charges
  - no


missing_vadarneg_words:
  - nuisance
  - dry
  - afraid
  - unfavorable
  - long
  - loud
  - high
  - busy
  - late
  - pointless
  - uncool
  - inappropriate
  - surprised
  - nothing
  - poorly
  - loathe
  - hideous

swap:
  - fail
  - failure
  - television
  - thunder
  - food


stop_words:
  - "me,am,has,those,yourselves,isn't,each,y,before,but,who,out,shan't,isn,ve,weren,up,how,don,and,
    were,aren,into,you're,them,can,in,ours,shan,don't,for,with,why,its,whom,keeps,him,is,our,
    needn't,hasn't,hasn,itself,of,you'll,any,only,over,both,wouldn,above,won't,she,does,by,just,
    shouldn't,these,i,should,which,until,yourself,m,wouldn't,we,down,a,herself,more,be,mightn't,
    she's,didn,himself,weren't,below,ll,re,lol,this,let,it,few,than,against,season,proctor,hadn,it's,from,are,honestly,
    under,pessimistic,pessimize,doesn't,mustn,i'm,about,nor,yours,feel,taken,duquette,got,buying,had,further,through,
    there,you,mightn,should've,own,all,you'd,you've,will,most,during,then,where,go,if,
    hers,getting,that'll,such,haven't,d,once,doesn,so,pearson,no,mustn't,after,won,wasn't,now,what,same,
    wasn,ourselves,aren't,couldn't,as,o,their,your,do,shouldn,on,hadn't,his,at,or,an,the,needn,haven,
    s,t,been,did,her,themselves,because,my,between,myself,to,didn't,ain,here,was,that,too,he,have,
    when,some,theirs,ma,couldn,other,off,having,always,obviously,im,bf,another,when,'re,n't,need,going"


missing:
  - very
  - sunday

nonoverlap:
  - job market
  - state
  - books
  - easily
  - amazing
  - fit of
  - attack
  - stuck
  - sitting
  - sapped
  - laundry
  - exams
  - vomiting
  - devoured
  - thought
  - human being
  - weather
  - paid
  - never got
  - heart
  - family
  - quiet
  - I'm
  - start
  - smile
  - moral
  - bilious
  - remember
  - Crazy
  - crazy
  - banned
  - squares
  - medicine
  - doctor
  - from cancer
  - meets
  - pleasure


quantifier:
  - one
  - three
  - '12'
  - 'zero'
  - 'Zero'

start:
  - not
  - very

replacement:
  - "women not ,women "
  - "way long ,long "
  - "being stuck ,stuck "
  - "sunday afternoons ,afternoons "
  - "not fun,fun "
  - "ten day ,"


wrongNE:
  - Jet
  - New
  - Drunk
  - Driving
  - London
  - Battery
  - Horror
  - Mid
  - Social

